export const movies= [
    {
        title: "Shawshank Redemption",
        image: "movie-1.jpg",
        year:"2001",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action",
        rating: "10",
        description: "The Shawshank Redemption is not a true story, but is based on a novella by Stephen King. The movie expands on the original source material and changes the fates of key characters. The prison scenes in The Shawshank Redemption were filmed in a real Ohio prison, adding to the believability of the story.",
        type: "Awesome",
        duration:"2h 30m",
        grouping:"trending",
    },

    {
        title: "Rio",
        image: "movie-2.jpg",
        year:"2011",
        cast: "Jesse Eisenberg, Anne Hathaway, Carlos Saldanha, Jemaine Clement",
        genre: "Comedy ",
        rating: "10",
        description: "When Blu, a domesticated macaw from small-town Minnesota, meets the fiercely independent Jewel, he takes off on an adventure to Rio de Janeiro with the bird of his dreams.",
        type: "Cute",
        duration:"1h 30m",
        grouping:"trending",
    },

    {
        title: "Aladdin",
        image: "movie-3.jpg",
        year:"2015",
        cast: "Will Smith, Mena Massoud, Naomi Scott",
        genre: "Adventure",
        rating: "15",
        description: "Aladdin, a kind thief, woos Jasmine, the princess of Agrabah, with the help of Genie. When Jafar, the grand vizier, tries to usurp the king, Jasmine, Aladdin and Genie must stop him from succeeding.",
        type: "Shesh",
        duration:"2h 45m",
        grouping:"trending",
    },

    {
        title: "Titanic",
        image: "movie-4.jpg",
        year:"2000",
        cast: "Kate Winslet, Leonardo DiCaprio, Billy Zane",
        genre: "Romance",
        rating: "20",
        description: "RMS Titanic was a British ocean liner that sank on 15 April 1912 after striking an iceberg on the ship's maiden voyage from Southampton, England to New York City, United States. Titanic, operated by the White Star Line, was carrying passengers and mail.",
        type: "Cry Cry",
        duration:"1h 25m",
        grouping:"trending",
    },

    {
        title: "Twilight",
        image: "movie-5.jpg",
        year:"2005",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "Romance",
        rating: "20",
        description: "The Twilight Saga is a series of romance fantasy films based on the book series Twilight by Stephenie Meyer. The series has grossed over $5.28 billion worldwide. The first installment, Twilight, was released on November 21, 2008. The second installment, New Moon, followed on November 20, 2009.",
        type: "Wow",
        duration:"2h 15m",
        grouping:"trending",
    },

    {
        title: "Moana",
        image: "movie-6.jpg",
        year:"2008",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"trending",
    },

    {
        title: "Fast and Furios",
        image: "movie-7.jpg",
        year:"2008",
        cast: " Vin Diesel, Louis Leterrier, James Wan, John Singleton, F. Gary Gray, Rob Cohen, Justin Lin",
        genre: "Adventure",
        rating: "23",
        description: "Fast & Furious, also known as The Fast and the Furious, is an American media franchise centered on a series of action films that are largely concerned with street racing, heists, spies, and family. The franchise also includes short films, a television series, toys, video games, live shows, and theme park attractions.",
        type: "Drive",
        duration:"1h 55m",
        grouping:"trending",
    },

    {
        title: "X-men",
        image: "movie-8.jpg",
        year:"2011",
        cast: " James Mangold, Gavin Hood, Brett Ratner, Matthew Vaughn, Simon Kinberg, Josh Boone, Bryan Singer",
        genre: "Thrill",
        rating: "10",
        description: "X-Men is an American superhero film series based on the Marvel Comics superhero team of the same name. 20th Century Fox obtained the film rights to the team and other related characters in 1994 for $2.6 million.",
        type: "Luh",
        duration:"2h 50mm",
        grouping:"asian",
    },

    {
        title: "Jurassic Park",
        image: "movie-9.jpg",
        year:"2001",
        cast: "Steven Spielberg",
        genre: "Thrill",
        rating: "19",
        description: "In Steven Spielberg's massive blockbuster, paleontologists Alan Grant (Sam Neill) and Ellie Sattler (Laura Dern) and mathematician Ian Malcolm (Jeff Goldblum) are among a select group chosen to tour an island theme park populated by dinosaurs created from prehistoric DNA. ",
        type: "Run",
        duration:"1h 09m",
        grouping:"asian",
    },

    {
        title: "Avatar",
        image: "movie-10.jpg",
        year:"2015",
        cast: "James Cameron, Jacob Black, Renesmee",
        genre: "Imaginative",
        rating: "15",
        description: "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
        type: "Wheeehhh",
        duration:"2h 55m",
        grouping:"asian",
    },

    {
        title: "Logan",
        image: "movie-11.jpg",
        year:"2000",
        cast: "Roy Thomas; Len Wein, John Romita Sr.",
        genre: "Action",
        rating: "20",
        description: "In the near future, a weary Logan (Hugh Jackman) cares for an ailing Professor X (Patrick Stewart) at a remote outpost on the Mexican border. ",
        type: "Yahhh",
        duration:"1h 20m",
        grouping:"asian",
    },

    {
        title: "1917",
        image: "movie-12.jpg",
        year:"2008",
        cast: "Dean-Charles Chapman, George MacKay, Daniel Mays",
        genre: "War",
        rating: "10",
        description: "During World War I, two British soldiers -- Lance Cpl. Schofield and Lance Cpl. Blake -- receive seemingly impossible orders. In a race against time, they must cross over into enemy territory to deliver a message that could potentially save 1,600 of their fellow comrades -- including Blake's own brother.",
        type: "Beng beng",
        duration:"1h 20m",
        grouping:"asian",
    },

    {
        title: "TinTin",
        image: "movie-13.jpg",
        year:"2012",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "Action",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"asian",
    },

    {
        title: "Lucy",
        image: "movie-14.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"asian",
    },

    {
        title: "Queen of Tears",
        number: "1.png",
        image: "top-1.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "2.png",
        image: "top-2.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "3.png",
        image: "top-3.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "4.png",
        image: "top-4.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "5.png",
        image: "top-5.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "6.png",
        image: "top-6.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "7.png",
        image: "top-7.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "8.png",
        image: "top-8.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "9.png",
        image: "top-9.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },

    {
        title: "Queen of Tears",
        number: "10.png",
        image: "top-10.jpg",
        year:"2002",
        cast: "Bella Swan, Edward Cullen, Jacob Black, Renesmee",
        genre: "SciFi",
        rating: "10",
        description: "Moana, also known as Vaiana[4] or Oceania[5] in some markets, is a 2016 American animated musical fantasy adventure film produced by Walt Disney Animation Studios and distributed by Walt Disney Pictures.",
        type: "Swim",
        duration:"1h 20m",
        grouping:"top",
    },
]
